create table public.contatos (
    id bigint generated by default as identity primary key,
    nome text not null
        check (length(trim(nome)) > 0),
    telefone text not null unique
        check (telefone ~ '^[1-9][0-9]{7,14}$'),
    ativo boolean not null default true,
    created_at timestamptz not null default now()
);

alter table public.contatos enable row level security;
